import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import SmoothAnimation from "./_components/SmoothAnimation";
import { VideoProvider } from "@/app/_context/VideoContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function OptibeltLayout({ children }: { children: React.ReactNode }) {
  return (
    <div
      className={`${geistSans.variable} ${geistMono.variable} min-h-full h-full antialiased flex flex-col`}
    >
        <VideoProvider>
          <SmoothAnimation />
          <Header />
          {children}
          <Footer />
        </VideoProvider>
    </div>
  );
}